### ISSUE TITLE
can't refresh under 3.65 enso posts

### ISSUE THREAD

**Issue by nictse2013** [CelesteBlue-dev/PSVita-StorageMgr#55] opened 2019-01-04 16:25 UTC
NoNpDrm doesn't work
other plugins works fine!

**Comment by CelesteBlue-dev** [comment] 2019-01-04 16:35
[config.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/2727680/config.txt)
try this config.txt in ur0:tai/ and remove ux0:tai/ folder.

**Comment by nictse2013** [comment] 2019-01-04 16:51
doesn't work at all...
forgot to say,i use usb as ux0,3.65 enso tv
i tried usbmc before, it can refresh the game, but such as "tearaway" show error c0-9250-6
usbmc need config like under steps https://www.reddit.com/r/VitaPiracy/comments/71s4mi/pstv_usbmc_nonpdrm_anyone_got_that_working/
so i tried this soft, can't refresh but can enter the "tearaway"without any error.

**Comment by CelesteBlue-dev** [comment] 2020-01-11 11:59
@nictse2013 I guess you have found a solution so I close this issue. You can still answer even though the issue is closed. Regards.

**Closed by CelesteBlue-dev** 2020-01-11 11:59 UTC
