### ISSUE TITLE
VitaShell and Adrenaline give an error if you try to run them from the Sony memory card

### ISSUE THREAD

**Issue by Checcolino** [CelesteBlue-dev/PSVita-StorageMgr#41] opened 2018-07-30 16:20 UTC
everything works ... only problem and when I choose to start vitashell or adrenaline that I own on the memory sony tells me damaged files ... how to correct the error? thank you so much

**Comment by itsminht** [comment] 2018-07-31 11:34
What is your current storagemgr setup?

**Comment by CelesteBlue-dev** [comment] 2020-01-11 13:32
I close this issue because it seams not caused by StorageMgr but by your setup. Reopen an issue if you need.

**Closed by CelesteBlue-dev** 2020-01-11 13:32 UTC
