### ISSUE TITLE
Support multiple partitions/greater than 2TB

### ISSUE THREAD

**Issue by t0mtaylor** [CelesteBlue-dev/PSVita-StorageMgr#53] opened 2018-11-14 15:09 UTC
Hi @CelesteBlue-dev 

Great work on the storage manager :)

Is it possible to support partitions larger than 2TB, or if you could use multiple partitions via:

- Multiple USB HDD

- Larger 2-4TB USB HDD with 2 or more partitions

The current 2TB hard drive (ExFat) im using only for the PSTV seems to be maxed out when i check on the PSTV both using content manager or Vita Shell v1.97 - even though MacOS says the ExFat drive is only using 180GB of data? (meaning 1.52TB of free space?)

Using PSVita v3.65 with v3 storagemgr.skprx

I have a 4TB external USB HDD that i could use to test, or use 2 partitions, just need a way for the storage manager to support it

Thanks :)

**Comment by CelesteBlue-dev** [comment] 2018-11-14 21:03
@t0mtaylor is your 2TB harddrive formatted in exFAT ?
(FAT32 is bad. And NTFS is not supported on PSVita.)

**Comment by CelesteBlue-dev** [comment] 2018-11-19 20:43
@t0mtaylor The issue is that FS limit is 2TB on PSVita. The onmy way to bypass it would be to change PSVita exFAT drivers, but it is pretty impossible. We don't have source code, so we can only do patches.
For exemple, >2TB support was added to PS2 not a lonf time ago, but the difference is that on PS2 we have source code.
On PS4, >2TB support was officially added in a PS4 update not a long time ago.

So nobody will do this. The limit will stay at 2TB, and so, dont use >2TB drives.
It may be annoying, but anyway nobody has so many vita games, and almost nobody has a 4TB HDD for now.

**Comment by t0mtaylor** [comment] 2018-11-19 20:54
@CelesteBlue-dev what about the option to mount a second partition to another mountpoint? could that be configured within the 'storage_config.txt' with an update to the StorageMgr - or would this require the source code so you can access multiple 2TB partitions from a single usb device?

**Comment by CelesteBlue-dev** [comment] 2018-11-19 20:59
USB mounting is done by a driver that doesn't support multi partitions.
It would be possible to read raw data from the HDD, but it won't be fast, easy to use, and will certainly not be mountable as a vita partition. It is possible to do that, but only a few people could do this, like xyz, yifan lu or motoharu, but they don't have time. Me no I.

So I close this issue. There are better things waiting for vita.

**Comment by richard1222** [comment] 2018-11-19 20:59
Can i threw in my 2 cents? Not to be a dick or anything but do you really need something bigger then 2tb? Thats a lot of games to play or even beat and i assume you got a job right?

**Closed by CelesteBlue-dev** 2018-11-19 20:59 UTC

**Comment by t0mtaylor** [comment] 2018-11-19 21:03
@richard1222 haha yes, it appears https://github.com/ONElua/AdrenalineBubbleManager uses alot of space when you generate bubbles for many software titles - its a decision between bubbles or no bubbles and just use Adrenaline directly

@CelesteBlue-dev thanks for the explanation and your time :)
